# 阶段化训练数据配置
# 版本: v1.0.0
# 更新时间: 2025-09-23

# 阶段定义和配置
stages:
  pretraining:
    name: "预训练阶段"
    description: "大规模基础数据集训练，建立模型基础能力"
    config_file: "stages/pretraining.json"
    priority: 1
    auto_switch_conditions:
      - epoch: 0
        condition: "start"
        description: "训练开始时自动进入预训练阶段"
    resource_requirements:
      min_gpu_memory: "16GB"
      recommended_batch_size: 32
      estimated_duration: "2-3 days"
    
  finetuning:
    name: "微调阶段" 
    description: "特定场景精细化训练，提升专项能力"
    config_file: "stages/finetuning.json"
    priority: 2
    auto_switch_conditions:
      - epoch: 50
        condition: "pretraining_complete"
        description: "预训练达到50个epoch后自动切换"
      - metric: "loss"
        threshold: 0.1
        operator: "<"
        description: "损失函数低于0.1时可以切换"
    resource_requirements:
      min_gpu_memory: "8GB"
      recommended_batch_size: 16
      estimated_duration: "1-2 days"
    
  evaluation:
    name: "评估阶段"
    description: "模型性能全面评估，生成评估报告"
    config_file: "stages/evaluation.json"
    priority: 3
    auto_switch_conditions:
      - epoch: 100
        condition: "training_complete"
        description: "训练完成后进入评估阶段"
    trigger_mode: "manual"  # 也可以设置为auto
    resource_requirements:
      min_gpu_memory: "4GB"
      recommended_batch_size: 8
      estimated_duration: "2-4 hours"
    
  online_learning:
    name: "在线学习阶段"
    description: "增量学习和模型实时更新"
    config_file: "stages/online_learning.json"
    priority: 4
    trigger_mode: "manual"  # 手动触发
    resource_requirements:
      min_gpu_memory: "8GB"
      recommended_batch_size: 4
      estimated_duration: "continuous"
    
  ab_testing:
    name: "A/B测试阶段"
    description: "对比实验数据集，验证不同策略效果"
    variants:
      variant_a:
        name: "控制组"
        description: "基准数据集配置"
        config_file: "stages/ab_testing/variant_a.json"
        weight: 0.5
      variant_b:
        name: "实验组"
        description: "优化后数据集配置"
        config_file: "stages/ab_testing/variant_b.json"
        weight: 0.5
    trigger_mode: "manual"
    resource_requirements:
      min_gpu_memory: "8GB"
      recommended_batch_size: 16
      estimated_duration: "1-3 days"

# 默认阶段
default_stage: "pretraining"

# 阶段切换策略
switch_strategy:
  mode: "hybrid"  # auto | manual | hybrid
  check_interval: 5  # 检查间隔(epoch)
  fallback_stage: "pretraining"
  auto_rollback: true  # 异常时自动回滚
  rollback_conditions:
    - metric: "loss"
      threshold: 10.0
      operator: ">"
      action: "rollback"
    - metric: "gpu_memory_usage"
      threshold: 0.95
      operator: ">"
      action: "pause"

# 全局配置
global_config:
  # 数据加载配置
  data_loader:
    num_workers: 4
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true
  
  # 缓存配置
  cache:
    enabled: true
    cache_dir: "/tmp/dataset_cache"
    max_cache_size: "10GB"
    clear_on_stage_switch: false
  
  # 日志配置
  logging:
    level: "INFO"
    log_file: "logs/stage_manager.log"
    log_rotation: "daily"
    max_log_files: 7
  
  # 监控配置
  monitoring:
    enabled: true
    metrics_interval: 60  # 秒
    alert_thresholds:
      data_loading_time: 30  # 秒
      memory_usage: 0.9
      disk_usage: 0.8

# 环境特定配置
environments:
  development:
    switch_strategy:
      mode: "manual"
    global_config:
      cache:
        max_cache_size: "1GB"
      logging:
        level: "DEBUG"
  
  production:
    switch_strategy:
      mode: "auto"
      check_interval: 10
    global_config:
      cache:
        max_cache_size: "50GB"
      monitoring:
        enabled: true
        alert_thresholds:
          data_loading_time: 10

# 兼容性配置
compatibility:
  # 向后兼容原有的training_dataset.json
  legacy_support: true
  legacy_config_file: "training_dataset.json"
  
  # DataSpecHub集成
  dataspec_integration:
    enabled: true
    consumer_version_validation: true
    bundle_version_tracking: true

# 安全配置
security:
  # 配置文件验证
  validate_config_signature: false
  allowed_config_paths:
    - "stages/"
    - "templates/"
  
  # 环境变量白名单
  allowed_env_vars:
    - "TRAINING_STAGE"
    - "AB_VARIANT"
    - "STAGE_CONFIG_PATH"
    - "FORCE_DATASET_CONFIG"

